create database QLNSu
use QLNSu



GO
DROP TABLE [CHITIETBANGCHAMCONG] 
GO
DROP TABLE [BANGCHAMCONG] 
GO
DROP TABLE [CHITIETBANGLUONG] 
GO
DROP TABLE [TRINHDOHOCVAN] 
GO
DROP TABLE [PHONGBAN] 
GO
DROP TABLE [BANGLUONG] 
GO
DROP TABLE [NHANVIEN] 
GO


CREATE TABLE [NHANVIEN]
(
	[MANV] VARCHAR NOT NULL,
	[TENNV] NVARCHAR NULL,
	[DIACHI] NVARCHAR NULL,
	[GIOITINH] BIT NULL,
	[NGAYSINH] DATE NULL,
	[DANTOC] NVARCHAR NULL,
	[MAPHONGBAN] NVARCHAR NOT NULL,
	[MATRINHDO] NVARCHAR NOT NULL
PRIMARY KEY ([MANV])
) 
GO

CREATE TABLE ACCOUNT(
	[IDACCOUNT] NVARCHAR,
	[USERNAME] NVARCHAR unique,
	[PASSWORD] NVARCHAR,
	[ROLE] int,
	[TRANGTHAI] int,
	[MANV] varchar not null,
	Primary key ([IDACCOUNT]),
	Foreign key (MANV) references NHANVIEN([MANV])
)
CREATE TABLE [BANGLUONG]
(
	[MABANGLUONG] NVARCHAR NOT NULL,
	[HESOPHUCAP] Float NULL,
	[HESOLUONG] Float NULL,
	[LUONGCOBAN] FLOAT NULL,
PRIMARY KEY ([MABANGLUONG])
) 
GO

CREATE TABLE [PHONGBAN]
(
	[MAPHONGBAN] NVARCHAR NOT NULL,
	[TENPHONGBAN] NVARCHAR NULL,
	[SOLUONGNHANVIEN] int NULL,
	[TRANGTHAI] int,
	PRIMARY KEY ([MAPHONGBAN])
) 
GO

CREATE TABLE [TRINHDOHOCVAN]
(
	[MATRINHDO] NVARCHAR NOT NULL,
	[TENTRINHDO] NVARCHAR NULL,
	[CHUYENNGANH] NVARCHAR NULL,
PRIMARY KEY ([MATRINHDO])
) 
GO

CREATE TABLE [CHITIETBANGLUONG]
(
	[MANV] VARCHAR NOT NULL,
	[MABANGLUONG] NVARCHAR NOT NULL,
	[SONGAYCONG] NVARCHAR NULL,
	[MABANGCHAMCONG] NVARCHAR NOT NULL,
PRIMARY KEY ([MANV],[MABANGLUONG])
) 
GO

CREATE TABLE [BANGCHAMCONG]
(
	[MABANGCHAMCONG] NVARCHAR NOT NULL,
PRIMARY KEY ([MABANGCHAMCONG])
) 
GO

CREATE TABLE [CHITIETBANGCHAMCONG]
(
	[MANV] VARCHAR NOT NULL,
	[MABANGCHAMCONG] NVARCHAR NOT NULL,
	[NGAYCHAMCONG] NVARCHAR NULL,
PRIMARY KEY ([MANV],[MABANGCHAMCONG])
) 

GO
ALTER TABLE [CHITIETBANGLUONG] ADD  FOREIGN KEY([MANV]) REFERENCES [NHANVIEN] ([MANV])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [CHITIETBANGCHAMCONG] ADD  FOREIGN KEY([MANV]) REFERENCES [NHANVIEN] ([MANV])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [CHITIETBANGLUONG] ADD  FOREIGN KEY([MABANGLUONG]) REFERENCES [BANGLUONG] ([MABANGLUONG])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [NHANVIEN] ADD  FOREIGN KEY([MAPHONGBAN]) REFERENCES [PHONGBAN] ([MAPHONGBAN])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [NHANVIEN] ADD  FOREIGN KEY([MATRINHDO]) REFERENCES [TRINHDOHOCVAN] ([MATRINHDO])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [CHITIETBANGCHAMCONG] ADD  FOREIGN KEY([MABANGCHAMCONG]) REFERENCES [BANGCHAMCONG] ([MABANGCHAMCONG])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO
ALTER TABLE [CHITIETBANGLUONG] ADD  FOREIGN KEY([MABANGCHAMCONG]) REFERENCES [BANGCHAMCONG] ([MABANGCHAMCONG])  ON UPDATE NO ACTION ON DELETE NO ACTION 
GO


SET QUOTED_IDENTIFIER ON
GO


SET QUOTED_IDENTIFIER OFF
GO
