CREATE DATABASE QLNS
GO
use B4

USE QLNS
GO
CREATE TABLE [BANGLUONG]
(
	[MABANGLUONG] Nvarchar(10) NOT NULL,
	[HESOPHUCAP] Float not NULL,
	[HESOLUONG] Float not NULL,
	[LUONGCOBAN] FLOAT NOT NULL,
	PRIMARY KEY ([MABANGLUONG])
)
CREATE TABLE CHUCVU(
	[MACHUCVU] varchar(10) not null,
	[TENCHUCVU] nvarchar(50) not null,
	PRIMARY KEY (MACHUCVU)
)
CREATE TABLE [PHONGBAN]
(
	[MAPHONGBAN] Nvarchar(10) NOT NULL,
	[TENPHONGBAN] Nvarchar(50) not NULL,
	[TRANGTHAI] int NOT NULL DEFAULT 0,
	PRIMARY KEY ([MAPHONGBAN])
)
CREATE TABLE [NHANVIEN]
(
	[MANV] VARCHAR(10) NOT NULL,
	[TENNV] Nvarchar(50)  not NULL,
	[DIACHI] Nvarchar(50) NULL,
	[GIOITINH] int NOT NULL,
	[NGAYSINH] DATE  NOT NULL,
	[MACHUCVU] varchar(10) not null,
	[MAPHONGBAN] Nvarchar(10) NOT NULL,
	[MABANGLUONG] nvarchar(10) not null,
	[TINHTRANG] nvarchar(50) not null,
	[Avatar] nvarchar(255) null ,
	PRIMARY KEY ([MANV]),
	FOREIGN KEY ([MACHUCVU]) REFERENCES CHUCVU([MACHUCVU]),
	FOREIGN KEY ([MABANGLUONG]) REFERENCES BANGLUONG([MABANGLUONG]),
	FOREIGN KEY ([MAPHONGBAN]) REFERENCES PHONGBAN([MAPHONGBAN])
) 

CREATE TABLE ACCOUNT(
	[IDACCOUNT] Nvarchar(10),
	[USERNAME] Nvarchar(50) unique,
	[PASSWORD] Nvarchar(500) not null,
	[ROLE] INT not null, 
	[TRANGTHAI] INT not null,
	[MANV] varchar(10) not null,
	Primary key ([IDACCOUNT]),
	Foreign key (MANV) references NHANVIEN([MANV])
)
CREATE TABLE [CHITIETBANGCHAMCONG]
(
	[MANV] varchar(10) NOT NULL,
	[NGAYCHAMCONG] date,
	[GIOVAO] time ,
	[GIORA] time,
	PRIMARY KEY([MANV],[NGAYCHAMCONG]),
	FOREIGN KEY([MANV]) REFERENCES [NHANVIEN] ([MANV])  ON UPDATE NO ACTION ON DELETE NO ACTION
)
Create table [QUANLYDON](
	[MADON] nvarchar(100),
	[MANV] varchar(10),
	[NgayLap] datetime not null,
	[NOIDUNG] nvarchar(250) not null,
	[TRANGTHAI] int default 0,
	Primary key ([MADON]),
	Foreign key ([MANV]) references NHANVIEN([MANV])
)
INSERT INTO PHONGBAN VALUES (N'ADMIN', N'ADMIN', 1)
INSERT INTO CHUCVU VALUES ('ADMIN', N'ADMIN')
INSERT INTO BANGLUONG VALUES ('ADMIN', 0, 0, 0)

set dateformat dmy

INSERT INTO NHANVIEN VALUES ('NV001','Pham Hoang Nhan', '12 abc', 1, '17/09/2003','ADMIN', 'ADMIN','ADMIN' ,'Dang Lam',null)

INSERT INTO ACCOUNT VALUES ('1','admin','e86f78a8a3caf0b60d8e74e5942aa6d86dc150cd3c03338aef25b7d2d7e3acc7',1,1,'NV001')

SELECT * FROM ACCOUNT


INSERT INTO PHONGBAN VALUES (N'CN', N'Công Nghệ', 1),(N'KD', N'Kinh Doanh', 1), (N'KT', N'Kế Toán', 1)
INSERT INTO CHUCVU VALUES ('QL', N'Quản Lý'), ('NV',N'Nhân Viên')

INSERT INTO BANGLUONG VALUES ('BL01', 3.2, 2.4, 4500000)

SELECT * FROM CHITIETBANGCHAMCONG

SELECT * FROM BANGLUONG
SELECT * FROM NHANVIEN where NGAYSINH = '17/09/2003'

SELECT CURRENT_TIMEZONE();  
